'use client'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from './Components/Navbar'
import Footer from './Components/Footer'
import StoreProvider from './StoreProvider'
import { useState } from 'react'
import style from './module.style.css'

const inter = Inter({ subsets: ['latin'] })

 const metadata = {
  title: 'Yingkiong Store',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {


  const [isLoggedIn, setIsLoggedIn] = useState(true);
  

  const handleLogin = () => {
    // Implement your login logic here
    setIsLoggedIn(true);
  };

  const handleLogout = () => {
    // Implement your logout logic here
    setIsLoggedIn(false);
  };

  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
        {isLoggedIn && <Navbar/>}
        {/* <Navbar/> */}
        {children}
        <Footer/>
        </StoreProvider>
   
        </body>
    </html>
  )
}
